### ISSUE TITLE
Records are out of order when creating ICL file

### ISSUE THREAD

**Issue by ryanmwetzel** [moov-io/imagecashletter#130] opened 2020-11-03 17:04 UTC
**What were you trying to do?**
Create an ICL from JSON with multiple checks.

**What did you expect to see?**
The records should be in the order 25, {50, 52}(check 1 - front), {50, 52}(check 1 - back) which has no addendum records.  Second check should be in the order 25, 26, 28, {50, 52}(check 2 - front), {50,52}(check 2 - back).  Any additional addendum records should also be in order following the 25 record (e.g. 27).  This also applies to return records, but not sure where they fall in the order as still testing on our end.

**What did you see?**
Order is 25, 50(check 1 -front), 50(check 2 - front), 52(check 1 - front), 52(check 1 - back) and 25, 26, 28, {50(check 2 -front), 50(check 2 - back), 52(check 2 - front), 52(check 2 - back).

**How can we reproduce the problem?**
Make it so the 52 record follows the corresponding front or back of a 50 record.

This is similar to issue #108

**Comment by atonks2** [comment] 2020-11-03 20:07
@ryanmwetzel I think I misunderstood. I thought when we talked about this you were talking about submitting a binary ICL file; I didn't realize you were using a JSON payload. That being the case I think this probably is the same as #108 (as you originally suggested). This seems to have a bit more detail on it, so perhaps we should keep this one and close 108. Thoughts @adamdecaf 

Also Ryan, if you have a JSON payload you can share that'd be very helpful in reproducing/testing this issue. Don't worry about it if you don't have an example that excludes sensitive information though.

**Comment by adamdecaf** [comment] 2020-11-11 23:01
`WriteCollatedImageViewOption()` and https://github.com/moov-io/imagecashletter/pull/132 should address this in the Go library and HTTP server. Can we close this? We can make another `v0.5.0-rcX` if needed. cc @atonks2

**Comment by atonks2** [comment] 2020-11-12 21:09
@ryanmwetzel Thanks again for reporting this. It seems to be fixed by #132, so I'll close it out. If there are still issues with the ordering of records in a file please let me know.

**Closed by atonks2** 2020-11-12 21:09 UTC
Labels: bug
