### ISSUE TITLE
file: Reading check details from JSON shuffles ordering 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/imagecashletter#108] opened 2020-08-05 16:45 UTC
From slack:

> Something I noticed while creating these...the records are out of order when using JSON if you have two check details (50) and views (52) under one check (25).  Meaning it goes 50 50 25 25 vs 50 25 50 25.  This would be how you create a front and back image changing the viewSideIndicator from 0 to 1 for back of the check.  It does however pick up the checks when using an ICL file...

**Comment by ryanmwetzel** [comment] 2020-10-30 13:51
@adamdecaf believe this was corrected in the recent release no?

**Comment by adamdecaf** [comment] 2020-10-30 14:49
I don't think this got fixed. JSON arrays are ordered (per the spec) and so are Go slices, but I could see these getting out of order. To be extra safe we should probably include an "order" integer or something.

**Comment by ryanmwetzel** [comment] 2020-10-30 15:23
You're correct.  It still needs to be ordered properly.

**Comment by adamdecaf** [comment] 2020-11-11 23:01
`WriteCollatedImageViewOption()` and https://github.com/moov-io/imagecashletter/pull/132 should address this in the Go library and HTTP server. Can we close this? We can make another `v0.5.0-rcX` if needed. cc @atonks2

**Comment by atonks2** [comment] 2020-11-12 21:07
Closing as duplicate of #130

**Closed by atonks2** 2020-11-12 21:07 UTC
Labels: bug
